### PR TITLE
[MNT] Removed `session_file_path` from aggregate results

### LINKED ISSUE #210: Remove session path values from aggregate results
Since the session paths we're currently returning contain BIDS subject identifiers, a valid concern is that even these paths are exposing too much identifying info for a supposedly 'secure' aggregate response.

To be safe, we will turn this off for the aggregate mode of the API so that the graph no longer returns the session paths.

See also #208

Looking ahead:
- When we eventually make the switch to having a two-part download process (for the dataset-level vs. participant-level TSV), we should consider not returning the participant-level TSV at all when the API is deployed in aggregate mode

### PR DESCRIPTION
**Pull request by rmanaem**
Closes #210 

Changes proposed in this pull request:

- Updated `create_query` function to not query `session_file_path`

## Checklist

- [x] PR has an interpretable title with a prefix (`[ENH]`, `[FIX]`, `[REF]`, `[TST]`, `[CI]`, `[MNT]`, `[INF]`, `[MODEL]`, `[DOC]`) _(see https://neurobagel.org/contributing/pull_requests for more info)_
- [x] PR links to GitHub issue with mention `Closes #XXXX`
- [x] Tests pass
- [x] Checks pass

For new features:
- [ ] Tests have been added

For bug fixes:
- [ ] There is at least one test that would fail under the original bug conditions.

### CODE REVIEW

**Review by alyssadai — COMMENTED** [review]
Thanks for the PR @rmanaem. I have a few implementation questions:
- A quick test of a local aggregate-mode API with your changes shows that the `subject_data` field still appears in the response, just as an empty list `[]`. Should we remove this key entirely from the aggregate response to avoid API user confusion? Or maybe populate it with an informative value like `"protected"`? 
- I noticed that this logic is still kicking around - not sure if we need it anymore
https://github.com/neurobagel/api/blob/47d3b7e720d29a9fd9b02f25343307e4d6bc6ed2/app/api/crud.py#L140-L144
- I see you reverted your initial change to the `test_data` aggregate response fixture, but I am in favour of updating it to reflect what the actual aggregate response looks like - wdyt?

Happy to have a chat about these decisions if that'd be helpful.

**Comment by rmanaem** [comment]
> A quick test of a local aggregate-mode API with your changes shows that the subject_data field still appears in the response, just as an empty list []. Should we remove this key entirely from the aggregate response to avoid API user confusion? Or maybe populate it with an informative value like "protected"?

I like the `protected` idea but to just to be sure is this `subject_data: ["protected"]` what you had in mind?

> I noticed that this logic is still kicking around - not sure if we need it anymore

Great catch, I'll get rid of that.

> I see you reverted your initial change to the test_data aggregate response fixture, but I am in favour of updating it to reflect what the actual aggregate response looks like - wdyt?

I don't have a preference but If we were to do that I'd say both subjects in the `test_data` should have their `subject_data` updated instead of just one like my commit did. wdyt?

**Comment by alyssadai** [comment]
> I like the `protected` idea but to just to be sure is this `subject_data: ["protected"]` what you had in mind?

I _think_ so, although you probably have a better sense of what would work best with the query tool. Since the API currently always expects a list of dicts for `subject_data`,
https://github.com/neurobagel/api/blob/47d3b7e720d29a9fd9b02f25343307e4d6bc6ed2/app/api/models.py#L63

I'm even wondering if we should just return `subject_data: "protected"` and make the model accept either a dict or a string value for this key. Alternatively, as said above, we could make this key entirely optional in the model.

> I don't have a preference but If we were to do that I'd say both subjects in the test_data should have their subject_data updated instead of just one like my commit did. wdyt?

Yes, since the fixture represents a single response I think all the subjects should be updated!

**Comment by rmanaem** [comment]
> I think so, although you probably have a better sense of what would work best with the query tool. Since the API currently always expects a list of dicts for subject_data,

Yea that's why I prefer the not removing the `subject_data` field. The query tool checks for that so I'd rather have it in the response even if it's empty.

> I'm even wondering if we should just return subject_data: "protected" and make the model accept either a dict or a string value for this key. Alternatively, as said above, we could make this key entirely optional in the model.

I had completely forgotten about that. I like the idea of extending the model to accept string values as well.

**Review by alyssadai — APPROVED** [review]
I think this looks good! 🧑‍🍳

**Pull request merged**
