### PR TITLE
[MNT] Switched to lifespan events

### LINKED ISSUE #152: Switch deprecated startup events to lifespan events
The `@app.on_event("startup")` syntax seems to be deprecated: https://fastapi.tiangolo.com/advanced/events/#alternative-events-deprecated and replaced by https://fastapi.tiangolo.com/advanced/events/#lifespan

We should look into updating the startup checks for defined credentials and allowed origins to follow this new syntax.

_Originally posted by @surchs in https://github.com/neurobagel/api/pull/151#discussion_r1310406775_

### PR DESCRIPTION
**Pull request by samadpls**
- Closes #152 

Changes proposed in this pull request:

- Replace startup and shutdown events with lifespan events

## Checklist

- [X] PR has an interpretable title with a prefix (`[ENH]`, `[FIX]`, `[REF]`, `[TST]`, `[CI]`, `[MNT]`, `[INF]`, `[MODEL]`, `[DOC]`) _(see https://neurobagel.org/contributing/pull_requests for more info)_
- [ ] PR has a label for the release changelog or `skip-release` (to be applied by maintainers only)
- [X] PR links to GitHub issue with mention `Closes #XXXX`
- [ ] Tests pass
- [ ] Checks pass

For new features:
- [ ] Tests have been added

For bug fixes:
- [ ] There is at least one test that would fail under the original bug conditions.

### CODE REVIEW

**Comment by samadpls** [comment]
@alyssadai , could you please review it whenever its convenient for you…

**Comment by alyssadai** [comment]
Hey @samadpls, thanks a lot for your PR, and sorry for the very long delay in review. The dev team has been unusually swamped over the past while given some urgent internal project tasks.

One of the maintainers get back to you as soon as we can. Thanks so much for your patience!

**Comment by samadpls** [comment]
Closing this PR due to its inactive status. I'd love to continue working on it if it receives reviews in the future. Thank you for the opportunity😊

**Comment by surchs** [comment]
@samadpls hey, that's fair - sorry this didn't work out as quickly as we would have liked here. We aim to have reviews come in quicker normally, but I think your PR slipped through the cracks because it was a busy time with many priorities.

Please do stay in touch and feel very welcome to contribute again on our repos! We'll make sure to stay on top of this in the future (we now have a "Community" section in our project board to help with that).

**Pull request closed without merging**
